---
name: Manual Trigger Workflow
on:
  workflow_run:
    workflows:
      - CI Tests
    types:
      - completed

jobs:
  manual-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Manual Step
        run: echo "This manual job can only run after the CI workflow passes."
