---
run-name: CI for ${{ github.event.repository.name }}
on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    permissions: write-all
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-2
      AWS_DEFAULT_REGION: ap-southeast-2

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - name: Install NPM dependencies
        run: |
          npm i

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          ./test.sh

      - name: Diff AWS CDK Stacks For Dev
        env:
          ENVIRONMENT: dev
        run: |
          npx cdk diff --require-approval never --no-asset-metadata --no-change-set
      
      - name: Diff AWS CDK Stacks For Prod
        env:
          ENVIRONMENT: prod
        run: |
          npx cdk diff --require-approval never --no-asset-metadata --no-change-set
    
  manual-job:
    needs: test # This ensures the manual job only runs if the 'test' job passes
    runs-on: ubuntu-latest
    if: ${{ success() }} # Ensures the job only runs if the 'test' job succeeds
    steps:
      - name: Manual Step
        run: echo "This is a manual job that can only be triggered manually."