---
run-name: AWS Dev Stack
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    permissions: write-all
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-2
      AWS_DEFAULT_REGION: ap-southeast-2

    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.aws_environment == 'Dev-Deploy' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - name: Install NPM dependencies
        run: |
          npm i

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          ./test.sh

      - name: Diff AWS CDK Stack for Dev
        env:
          ENVIRONMENT: dev
        run: |
          npx cdk diff --require-approval never --no-asset-metadata --no-change-set
          npx cdk synth --all --require-approval never --no-asset-metadata --no-change-set

      - name: Synth AWS CDK Stack for Dev
        env:
          ENVIRONMENT: dev
        run: |
          npx cdk synth --all --require-approval never --no-asset-metadata --no-change-set

      - name: Diff AWS CDK Stack for Prod
        env:
          ENVIRONMENT: prod
        run: |
          echo "Prod not implemented yet"
          # npx cdk diff --require-approval never --no-asset-metadata --no-change-set

  deploy-dev:
    permissions: write-all
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-2
      AWS_DEFAULT_REGION: ap-southeast-2
      ENVIRONMENT: dev
    needs: test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - name: Install NPM dependencies
        run: |
          npm i

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Using CDK
        run: |
          npx cdk bootstrap
          npx cdk deploy --all --ci --require-approval never
